package com.teamone.dao;

import org.apache.ibatis.annotations.Param;

import com.teamone.entity.Custom;

public interface CustomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom
     *
     * @mbggenerated Fri Jul 28 15:07:17 CST 2017
     */
    int deleteByPrimaryKey(String cardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom
     *
     * @mbggenerated Fri Jul 28 15:07:17 CST 2017
     */
    int insert(Custom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom
     *
     * @mbggenerated Fri Jul 28 15:07:17 CST 2017
     */
    int insertSelective(Custom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom
     *
     * @mbggenerated Fri Jul 28 15:07:17 CST 2017
     */
    Custom selectByPrimaryKey(String cardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom
     *
     * @mbggenerated Fri Jul 28 15:07:17 CST 2017
     */
    //通过主键更新顾客余额
    int updateByPrimaryKeySelective(Custom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom
     *
     * @mbggenerated Fri Jul 28 15:07:17 CST 2017
     */
    
    int updateByPrimaryKey(Custom record);
    
    /**
     * @author mian
     *根据卡号与身份证查询
     */
    Custom selectBycardIdAndId(@Param("cardId") String cardId,@Param("id") String Id);
    
    //根据卡号查个人信息
    Custom selectByCardId(String cardId);
    
}