package com.teamone.dao;

import java.util.List;

import com.teamone.entity.Bill;

public interface BillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbggenerated Wed Aug 02 10:51:58 CST 2017
     */
    int deleteByPrimaryKey(Long billId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbggenerated Wed Aug 02 10:51:58 CST 2017
     */
    int insert(Bill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbggenerated Wed Aug 02 10:51:58 CST 2017
     */
    int insertSelective(Bill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbggenerated Wed Aug 02 10:51:58 CST 2017
     */
    Bill selectByPrimaryKey(Long billId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbggenerated Wed Aug 02 10:51:58 CST 2017
     */
    int updateByPrimaryKeySelective(Bill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbggenerated Wed Aug 02 10:51:58 CST 2017
     */
    int updateByPrimaryKey(Bill record);

	List<Bill> selectAll();

	List<Bill> queryMore(Bill billsearch);
	
	Bill queryAccount(String account);
}